config/routes.rb
NewAuthDemo::Application.routes.draw do
  get "/home", to: "static_pages#home"
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"

  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  root :to => "users#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAuthDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	</head>
	<body data-spy="scroll" data-target="#home-sidebar" >

		<nav class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse"
						data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav" style="width:100%">
						<div class="row">
							<%= link_to "Home", "/home", class: "navvybtn-l btn-primary"%>
							<%= link_to "Contact", "/contact", class: "navvybtn-l btn-primary"%>
							<%= link_to "About", "/about", class: "navvybtn-l btn-primary"%>

					    <% if signed_in? %>
						    <li>
									<%=button_to "Sign Out", session_url, :method => :delete,
										:class => "navvybtn-r btn-danger" %>
								</li>
					      <li class="navbar-text navbar-left">
									Signed in as: <%= current_user.username %>
								</li>
					    <% else %>
								<%= link_to "Sign Up", new_user_url, class: "navvybtn-r btn-warning" %>
								<%= link_to "Sign In", new_session_url,	class: "navvybtn-r btn-success"%>
					    <% end %>



						</div>
					</ul>
				</div>
			</div>
		</nav>

    <% if flash[:errors] %>
    <ul style="color:red;text-shadow: 1px 1px 1px black;">
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <br>
    <% end %>

		<div class="container text-center">
	    <%= yield %>
		</div>

  </body>
</html>

app/views/static_pages/about.html.erb
<div class="jumbotron row text-center">
	<marquee scrollamount="25"><h1 style="color: #00ff00;">CA$H 4 GRAVE$</h1></marquee>
	<div class="col-xs-5 col-xs-offset-1">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor pretium odio sed dignissim. Maecenas congue est eget sem eleifend, nec facilisis felis lacinia. Sed ipsum felis, tincidunt vitae nunc nec, pharetra pulvinar ante. In hendrerit pellentesque placerat.</p>
	</div>
	<div class="col-xs-5 col-xs-offset-1">
		<p>Sed viverra justo dui, quis pellentesque augue interdum tempus. Sed viverra, arcu porta tincidunt lacinia, urna purus suscipit magna, vel vestibulum nisi massa a sapien. Duis in turpis sed felis volutpat scelerisque. Ut luctus vestibulum tincidunt. Donec imperdiet aliquet neque.</p>
	</div>
</div>

<div class="row text-center">
	<h1>Meet the TEAM!!</h1>
</div>

<div class="row text-center">
	<div class="col-xs-3">
		<img src="http://placekitten.com/300/300" class="img-circle img-responsive">
		<h2>Gizmo</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor pretium odio sed dignissim. Maecenas congue est eget sem eleifend, nec facilisis felis lacinia. Sed ipsum felis, tincidunt vitae nunc nec, pharetra pulvinar ante. In hendrerit pellentesque placerat.</p>
	</div>
	<div class="col-xs-3">
		<img src="http://placekitten.com/301/301" class="img-circle img-responsive">
		<h2>Breakfast</h2>
		<p>Sed viverra justo dui, quis pellentesque augue interdum tempus. Sed viverra, arcu porta tincidunt lacinia, urna purus suscipit magna, vel vestibulum nisi massa a sapien. Duis in turpis sed felis volutpat scelerisque. Ut luctus vestibulum tincidunt. Donec imperdiet aliquet neque.</p>
	</div>
	<div class="col-xs-3">
		<img src="http://placekitten.com/302/302" class="img-circle img-responsive">
		<h2>Earl</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor pretium odio sed dignissim. Maecenas congue est eget sem eleifend, nec facilisis felis lacinia. Sed ipsum felis, tincidunt vitae nunc nec, pharetra pulvinar ante. In hendrerit pellentesque placerat.</p>
	</div>
	<div class="col-xs-3">
		<img src="http://placekitten.com/299/299" class="img-circle img-responsive">
		<h2>Ajax</h2>
		<p>Sed viverra justo dui, quis pellentesque augue interdum tempus. Sed viverra, arcu porta tincidunt lacinia, urna purus suscipit magna, vel vestibulum nisi massa a sapien. Duis in turpis sed felis volutpat scelerisque. Ut luctus vestibulum tincidunt. Donec imperdiet aliquet neque.</p>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
	<div class="col-xs-5">
		<h1>Contact Me</h1>
		<div id="form-messages">

		</div>
		<form id="contact-form">
			<div class="form-group row">
				<div class="contact-form" id="contact-form-name">
				  <input
				     type="text"
						 class="form-control"
						 placeholder="Name">
				</div>

				<br>
				<div class="input-group contact-form" id="contact-form-email">
				  <span class="input-group-addon">Email</span>
				  <input
				     type="text"
						 class="form-control">
				</div>
		  </div>
			<hr>

			<div class="form-group row">
				<div class="contact-form" id="contact-form-subject">
				  <input
				     type="text"
						 class="form-control"
						 placeholder="Subject">
				</div>

				<br>
				<div class="contact-form" id="contact-form-message">
				  <textarea
					   rows="8"
						 cols="80"
						 class="form-control"
						 placeholder="Message"></textarea>
				</div>
		  </div>

			<p style="text-align:left"><input type="submit" class="btn btn-primary"
				id="contact-btn" value="Send &rarr;"></p>
		</form>
	</div>

	<div class="col-xs-5 col-xs-offset-1">
		<h1>Our Staff</h1>
		<div class="row">
			<table class="table table-striped table-bordered" id="staff-table">
				<tr>
					<th class="col-xs-6">Name</th>
					<th class="col-xs-6">Phone</th>
				</tr>
				<tr>
					<td class="col-xs-6">John Doe</td>
					<td class="col-xs-6">(123) 456-7890</td>
				</tr>
				<tr>
					<td class="col-xs-6">Mary Sue</td>
					<td class="col-xs-6">(987) 654-3210</td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="row text-center">
	<div id="wheeeee" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="wheeeee" data-slide-to="0" class="active">
			<% (1..3).each do |index| %>
				<li data-target="wheeeee" data-slide-to="<%= index %>">
			<% end %>
		</ol>

		<div class="carousel-inner">
			<div class="item active">
				<img src="http://placekitten.com/499/300">
				<div class="carousel-caption">
					LOOK AT THIS KITTEN HOMG
				</div>
			</div>
			<div class="item">
				<img src="http://placekitten.com/499/301">
				<div class="carousel-caption">
					THIS KITTEN IS SO COO
				</div>
			</div>
			<div class="item">
				<img src="http://placekitten.com/501/301">
				<div class="carousel-caption">
					AND IF YOU SELL YOUR GRAVE FOR GOLD
				</div>
			</div>
			<div class="item">
				<img src="http://placekitten.com/501/299">
				<div class="carousel-caption">
					THEN YOU CAN BE COO TOO
				</div>
			</div>
		</div>

		<a class="left carousel-control" href="#wheeeee" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left"></span>
		</a>
		<a class="right carousel-control" href="#wheeeee" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right"></span>
		</a>
	</div>
</div>


<div class="row">
	<div class="col-xs-3 affix-top" id="home-sidebar">
		<ul class="nav nav-stacked">
			<li><a href="#Pellentesque">Pellentesque</a></li>
			<li><a href="#Lobortis">Lobortis</a></li>
		</ul>
	</div>
	<div class="col-xs-9" id="home-lorem-text">
		<h3 id="Pellentesque">
			Pellentesque sit amet nisi eget nunc malesuada laoreet et nec ante.
		</h3>
		<p>Pellentesque porta leo sed mauris vestibulum, ac <a id="consectetur" data-toggle="tooltip" href="#">consectetur</a> neque commodo. Sed aliquam lacus eget dolor cursus blandit.

			Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin et est vestibulum, venenatis mi a, laoreet nibh. Phasellus id nisi varius, mattis leo at, molestie nisi. Suspendisse ultricies sem eu vestibulum bibendum. Maecenas euismod tortor vel dui vehicula convallis. In fermentum lacinia risus quis egestas.</p>
		<h3 id="Lobortis">
			 Lobortis magna nunc, sit amet posuere odio condimentum varius.
		</h3>
		<p>Proin condimentum tortor eget vulputate placerat. Duis condimentum, elit nec eleifend tristique, quam massa rutrum odio, ac fringilla sapien mi id orci. Vestibulum aliquam lacus et dictum volutpat. Donec posuere lorem velit, eu iaculis libero varius nec. Maecenas consectetur ipsum porttitor magna convallis semper.</p>

		<h3>Pellentesque sit amet nisi eget nunc malesuada laoreet et nec ante.</h3>
		<p>Pellentesque porta leo sed mauris vestibulum, ac consecteturneque commodo. Sed aliquam lacus eget dolor cursus blandit.

			Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin et est vestibulum, venenatis mi a, laoreet nibh. Phasellus id nisi varius, mattis leo at, molestie nisi. Suspendisse ultricies sem eu vestibulum bibendum. Maecenas euismod tortor vel dui vehicula convallis. In fermentum lacinia risus quis egestas.</p>

		<h3>Lobortis magna nunc, sit amet posuere odio condimentum varius.</h3>
		<p>Proin condimentum tortor eget vulputate placerat. Duis condimentum, elit nec eleifend tristique, quam massa rutrum odio, ac fringilla sapien mi id orci. Vestibulum aliquam lacus et dictum volutpat. Donec posuere lorem velit, eu iaculis libero varius nec. Maecenas consectetur ipsum porttitor magna convallis semper.</p>

		<h3>Pellentesque sit amet nisi eget nunc malesuada laoreet et nec ante.</h3>
		<p>Pellentesque porta leo sed mauris vestibulum, ac consecteturneque commodo. Sed aliquam lacus eget dolor cursus blandit.

			Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin et est vestibulum, venenatis mi a, laoreet nibh. Phasellus id nisi varius, mattis leo at, molestie nisi. Suspendisse ultricies sem eu vestibulum bibendum. Maecenas euismod tortor vel dui vehicula convallis. In fermentum lacinia risus quis egestas.</p>

		<h3>Lobortis magna nunc, sit amet posuere odio condimentum varius.</h3>
		<p>Proin condimentum tortor eget vulputate placerat. Duis condimentum, elit nec eleifend tristique, quam massa rutrum odio, ac fringilla sapien mi id orci. Vestibulum aliquam lacus et dictum volutpat. Donec posuere lorem velit, eu iaculis libero varius nec. Maecenas consectetur ipsum porttitor magna convallis semper.</p>

		<h3>Pellentesque sit amet nisi eget nunc malesuada laoreet et nec ante.</h3>
		<p>Pellentesque porta leo sed mauris vestibulum, ac consecteturneque commodo. Sed aliquam lacus eget dolor cursus blandit.

			Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin et est vestibulum, venenatis mi a, laoreet nibh. Phasellus id nisi varius, mattis leo at, molestie nisi. Suspendisse ultricies sem eu vestibulum bibendum. Maecenas euismod tortor vel dui vehicula convallis. In fermentum lacinia risus quis egestas.</p>

		<h3>Lobortis magna nunc, sit amet posuere odio condimentum varius.</h3>
		<p>Proin condimentum tortor eget vulputate placerat. Duis condimentum, elit nec eleifend tristique, quam massa rutrum odio, ac fringilla sapien mi id orci. Vestibulum aliquam lacus et dictum volutpat. Donec posuere lorem velit, eu iaculis libero varius nec. Maecenas consectetur ipsum porttitor magna convallis semper.</p>
	</div>
</div>

app/views/users/_form.html.erb
<% action = (params[:controller] == "sessions" ? session_url :
							(user.persisted? ? user_url(user) : users_url)) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>
<hr>
<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

	<div class="form-group row container">
		<div class="input-group col-xs-4">
		  <span class="input-group-addon">Username</span>
		  <input
		     id="user_username"
		     name="user[username]"
		     type="text"
				 class="form-control">
		</div>
  </div>

	<div class="form-group row container">
		<div class="input-group col-xs-4">
		  <span class="input-group-addon">Password</span>
		  <input
		     id="user_password"
		     name="user[password]"
		     type="password"
				 class="form-control">
		</div>
  </div>

  <input class="btn btn-success" type="submit" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>